### ISSUE TITLE
Mozilla Iceweasel 31.0 isn't using profile from firefox-profile

### ISSUE THREAD

**Issue by dman777** [saadtazi/firefox-profile-js#50]
For headless e2e testing, I am using Debian's Firefox fork called `iceweasel`. `firefox-profile` doesn't seem to effect `iceweasel` at all. I am using this pluging to click on a download link an download automatically with settings in profile. It works on a Mac Firefox, but not debian. Any suggestions, please? 

```
root@jenkins-agent-nodejs-001:~# firefox --version
Mozilla Iceweasel 31.0
```

**Comment by saadtazi** [comment]
Sorry, but I know nothing about iceweasel. I am not sur I understand how you are using `firefox-profile`. Are you creating a profile from scratch and trying to use it with selenium?
If it works in regular firefox, it is probably somerhing that does not work the same way with iceweasel.

Can you try to use selenium ruby or python library with iceweasel and check if it works?

**Comment by dman777** [comment]
```javascript 
var Promise = require('bluebird');
var FirefoxProfile = require('firefox-profile');

exports.getFirefoxProfile = function() {
  return new Promise(function(resolve, reject) {
    var firefoxProfile = new FirefoxProfile();
    firefoxProfile.setPreference('browser.download.dir',__dirname);
    firefoxProfile.setPreference('browser.download.useDownloadDir',true);
    firefoxProfile.setPreference('browser.download.folderList',2);
    firefoxProfile.setPreference("browser.helperApps.neverAsk.saveToDisk","text/csv");
    firefoxProfile.encoded(function(encodedProfile) {
      var multiCapabilities = [{
        browserName: 'firefox',
        firefox_profile : encodedProfile
      }];
      resolve(multiCapabilities);
    });
  });
}
```

I am using this with `getMultiCapabilities: helper.getFirefoxProfile` in a protractor config file. 

To be clear...when running on a Mac laptop, it works with no issues...the download settings take effect. But when placed on a Debian server with Debian's fork of firefox, that firefox is not effected by the profile and the download settings do not take effect.

**Comment by saadtazi** [comment]
Sorry, I didn't get a chance to try it on Debian with Iceweasel: were you able to find out if Iceweasel profiles are handled the same way as ff profiles? Did you try with another webdriver lib that handles FF profiles?

**Comment by saadtazi** [comment]
Closing. Reopen if you think it is related to `firefox-profile`...
