### ISSUE TITLE
Did you experience quirk when cloning profile?

### ISSUE THREAD

**Issue by Noitidart** [saadtazi/firefox-profile-js#56]
I just discovered this repo and am going to dig into it, but before I did I wanted to mention/ask something.

In the past year I worked on a clone profile method.

What I did was:

1. I copy the profile folder, and paste it with a new name in the firefox profiles folder: `"C:\Users\Vayeate\AppData\Roaming\Mozilla\Firefox\Profiles\new name here", I do this regardless of `IsRelativ=1`, meaning even if it was absolute path, the clone profile, is a relative.
2. I duplicate the entry in `profiles.ini` and set `IsRelative` to `=1`.

Then on startup of this clone profile, sometimes it starts as if its a brand new fresh profile. It should respect and be same as that old profile. Did you witness this?

**Comment by Noitidart** [comment]
Heres a video showing the quirk: https://www.youtube.com/watch?v=0Tt5tL6FJcI%3C/p%3E

**Comment by saadtazi** [comment]
Hi,
I have to admit that I didn't clone profile that often ... Please let me what your findings.

**Comment by Noitidart** [comment]
Ah ok thanks Ill check it out. Can you please state your logic on what you copy and stuff. It will help me read the code :)

**Comment by saadtazi** [comment]
Not sure how you use `firefox-profile` (through cli or programmatically), but here is some info about the "copy profile" feature:

the "copy" starts here: https://github.com/saadtazi/firefox-profile-js/blob/master/lib/firefox_profile.js#L202

- find the existing profile by profile name, and in which folder this profile is stored (firefox_profile.js, line 207)
- we copy the profile, **which litterally means copying the original folder (`profileDirectory`) into a new directory** (https://github.com/saadtazi/firefox-profile-js/blob/master/lib/firefox_profile.js#L182)

How we check if the existing profile exists and in which folder it is: it is done by `lib/profile_finder.js`: https://github.com/saadtazi/firefox-profile-js/blob/master/lib/profile_finder.js... We basically read the user `profiles.ini` file

**Comment by Noitidart** [comment]
Ah ok thank you! So you don't edit the profiles.ini it seems is this true?

I found out the meanings of forceDelete etc, it was on npm wrench :)

I am including this into a firefox addon.:)

**Comment by saadtazi** [comment]
No I am not adding those copied profiles to `profiles.ini`, the main purpose of this library is about creating profiles for selenium tests or extension development (this is how ˋjpm` package is using it).
That been said, it can be extended to add the newly created profile in profiles.ini. not sure if it will solve your problem though... Let me know if you would like to have this feature.
Note that PRs are more than welcome ;)

**Comment by Noitidart** [comment]
Thanks very much for your awesome communication and willingness to collaborate. I will keep you updated. :)

**Comment by Noitidart** [comment]
I'm working on clone functionality right now and will update you soon so you can close this out. THanks so much for leaving open for 2 mnths!

**Comment by Noitidart** [comment]
I think the issue was I was copying the parent.lock / .parentlock file && I was copying the local directory contents as well. Now I am creating an empty local directory (if `IsRelative=1`) and am not copying parent.lock/.parentlock and I don't see this quirk anymore! Thank you for your awesome work!

**Comment by saadtazi** [comment]
Glad you figure it out!
