### ISSUE TITLE
Support WebExtensions

### ISSUE THREAD

**Issue by vladikoff** [saadtazi/firefox-profile-js#57]
Hello Saad! I have issue loading an extension built with the new [WebExtensions](https://wiki.mozilla.org/WebExtensions) format 
### STR
- Get the extension from dist of https://github.com/vladikoff/fxa-dev-extension
- try loading it:

```
    fxaProfile.addExtension(__dirname + '/../node_modules/fxa-dev-extension/dist/fxa-dev.xpi', function() {
      fxaProfile.encoded(cb);
    })
```
### Expected

Should load the extension
### Actual

```

Error: Cannot find module '/var/folders/_z/8gy7l13n7yx4mdtmz4_xz_j00000gn/T/b3340956-4d68-4847-9558-6241120cd320fxa-dev.xpi/package.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at FirefoxProfile._addonDetails (/Users/vladikoff/mozilla/fxa-local-dev/node_modules/firefox-profile/lib/firefox_profile.js:633:20)
    at FirefoxProfile._installExtension (/Users/vladikoff/mozilla/fxa-local-dev/node_modules/firefox-profile/lib/firefox_profile.js:549:8)
    at FirefoxProfile.addExtension (/Users/vladikoff/mozilla/fxa-local-dev/node_modules/firefox-profile/lib/firefox_profile.js:319:8)
    at module.exports (/Users/vladikoff/mozilla/fxa-local-dev/_scripts/profile.js:109:16)
    at /Users/vladikoff/mozilla/fxa-local-dev/_scripts/start.js:36:5
    at started (/Users/vladikoff/mozilla/fxa-local-dev/node_modules/selenium-standalone/lib/start.js:81:7)
```
### Details

This code here looks for package.json: 

https://github.com/saadtazi/firefox-profile-js/blob/master/lib/firefox_profile.js#L633

AFAIK package.json is not used anymore

``` javascript
  // Attempt to parse the `install.rdf` inside the extension
  var doc;
  try {
    doc = fs.readFileSync(path.join(addonPath, 'install.rdf'));
  }
  // If not found, this is probably a jetpack style addon, so parse
  // the `package.json` file for addon details
  catch (e) {
    var manifest = require(path.join(addonPath, 'package.json'));
    // Jetpack addons are packed by default
    details.unpack = false;
    details.isNative = true;
    Object.keys(details).forEach(function (prop) {
      if (manifest[prop] !== undefined) {
        details[prop] = manifest[prop];
      }
    });

    cb && cb(details);
    return;
  }
```

I don't have time to investigate this further, but I might in a few days.

**Comment by saadtazi** [comment]
Thanks for the feedback.
Initially this package only supported `rdf` file, then someone from mozilla contributed and added support for package.json (so it can be used in the [jpm package](https://www.npmjs.com/package/jpm).

I have  to admit that i am not really following what's going on with firefox extensions devlopment. Do you know if ˋpackage.json` has been replaced by ˋmanifest.json` In jpm too?

**Comment by saadtazi** [comment]
According to [this](https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Getting_Started_%28jpm%29), jpm still uses package.json. I think we should keep package.json. Maybe @jsantell knows better?

**Comment by vladikoff** [comment]
> According to this, jpm still uses package.json. I think we should keep package.json. Maybe @jsantell knows better?

Yeah I guess we will need to support all 3. where the new one is `manifest.json`
