### ISSUE TITLE
Cannot set browser.download.dir

### ISSUE THREAD

**Issue by DFreds** [saadtazi/firefox-profile-js#60]
I am unable to set the browser.download.dir preference. I'm not sure if this is a Firefox issue or not. 

If I call setPreference("browser.download.dir", "C:\\\Temp"), the download directory gets set to C:Temp. It strips out the backslashes no matter what I do and ends up using the default downloads directory.

**Comment by saadtazi** [comment]
Hello,
I am not in front of a computer... I'll check later. In the meantime: did you try with `setPreference("browser.download.dir", "C:\\Temp");` (double back-slash)

**Comment by saadtazi** [comment]
I tried a double back slash (with someother prefs because I don't have a windows machine...):
```
...
fp.setPreference('some.custom.pref', 'con\sole');
fp.setPreference('some.custom.otherpref', 'con\\sole');
```
```
This is what I get:
![image](https://cloud.githubusercontent.com/assets/168223/14728726/8ec12de2-0805-11e6-9006-5769309de89a.png)
So a double-backslash should solve your problem. If that's the case, feel free to close the issue.

Thanks

**Comment by DFreds** [comment]
When I tried it with a double backslash and even a triple backslash just to see, and in both cases it stripped them out so I still had C:Test. Maybe it's specifically related to the download dir preference in Firefox?

**Comment by saadtazi** [comment]
So:
* I downloaded a Windows 10 Virtual machine
* I installed nodejs 5, selenium-standalone, firefox-profile, wd (a selenium webdriver lib)
* I created a test script:
```
// test.js
var FirefoxProfile = require('firefox-profile'),
    wd = require('wd');

// set some userPrefs if needed
// Note: make sure you call encoded() after setting some userPrefs
var fp = new FirefoxProfile();
// set "browser.download.dir" using double backslash
fp.setPreference("browser.download.dir", 'C:\\Users\\IEUser\\Desktop');
// see https://groups.google.com/d/msg/selenium-users/naWsM-bqHcs/L3CDv5z2etoJ
fp.setPreference("browser.download.folderList", 2);
// done with prefs?
fp.updatePreferences();

fp.encoded(function(zippedProfile) {
    console.log(zippedProfile);
    browser = wd.promiseChainRemote();
    browser.init({
      browserName:'firefox',
      // set firefox_profile capabilities HERE!!!!
      firefox_profile: zippedProfile
    }).
    // woOot!!
    get('https://en.wikipedia.org/wiki/Main_Page').then(function () {
        return new Promise(function(resolve) {
            setTimeout(function () { resolve(); }, 1000000);
        });
    }).done();
});
```

then `node test.js`: **this works perfectly for me**: 
![image](https://cloud.githubusercontent.com/assets/168223/14765065/34c51d04-099e-11e6-8709-9ab06d31c920.png)

----

![image](https://cloud.githubusercontent.com/assets/168223/14765069/85efdde0-099e-11e6-8686-f84d98cb9454.png)
```
// npm list
firefox-profile@0.3.13
wd@0.4.0
// node -v
v5.11.0
// npm -v
3.8.6
```
I hope this helps. Let me know

**Comment by DFreds** [comment]
Okay, thanks for your response. I'll look into this more and close the issue.

**Comment by saadtazi** [comment]
Don't hesitate to ask more for more help if needed

**Comment by meenakshidembi** [comment]
I am able to see that the download path for Firefox is getting set to whatever is mentioned in the. I just separated the code for firefox profile and not have it in the same test file. Please let me know how that can be done?

**Comment by saadtazi** [comment]
@meenakshidembi firefox-profile is tested with node 0.12, 4 and 6. So you can safely use node 4.

I am not sure i fully understand your first question about _separating the code_.
I assume that you might want to create a new js file the exports an async function that accepts some options and a callback function as parameter, and "return asynchronously" a browser:

```
// new file browser.js for example
// test.js
var FirefoxProfile = require('firefox-profile'),
    wd = require('wd');

// note: you can change the param to accept more options if needed...
module.exports = function getBrowser(downloadDir, cb) {
    var fp = new FirefoxProfile();
    fp.setPreference("browser.download.dir", downloadDir);
    fp.updatePreferences();

    fp.encoded(function(zippedProfile) {
        browser = wd.promiseChainRemote();
        browser.init({
          browserName:'firefox',
          // set firefox_profile capabilities HERE!!!!
          firefox_profile: zippedProfile
    });
    cb(null, brower);
});```

in your test files:
```
var getBrowser = require('./path/to/browser.js');

getBrowser('C:\\Users\\IEUser\\Desktop', function (err, browser) {
  // start testing here
});
```
(this code is not tested...)

Let me know if that doesn't answer your question.

**Comment by meenakshidembi** [comment]
Hi,
Thanks for your prompt reply.

My exact requirement is to run the test on *multiple browser *i am able to
complete the same on Chrome but i am stuck with setting the preference for
*firefox*.

What I meant in my question was precisely what you have understood.

But the fix you have give is setting the path for download but the test is
not getting executed. Also I observed that when the test is started one
instance of firefox is invoked and closed immediately and then the other
instance is invoked and that one does not get closed.

Below is how i have segregated the code on my machine. I have tweaked the
code little bit because i am setting more than one preferences.

This file i have named as *helper.js*

var FirefoxProfile = require('firefox-profile'),
    wd = require('wd');

module.exports = function getBrowser(cb) {
    var firefoxProfile = new FirefoxProfile();
    firefoxProfile.setPreference("browser.download.folderList", 2);
    firefoxProfile.setPreference("browser.download.manager.showWhenStarting",
false);
    firefoxProfile.setPreference("browser.download.dir",
'C:\\workflow_file_download');
    firefoxProfile.updatePreferences();

    firefoxProfile.encoded(function (zippedProfile) {
        browser = wd.promiseChainRemote();
        browser.init({
            browserName: 'firefox',
            // set firefox_profile capabilities HERE!!!!
            firefox_profile: zippedProfile
        });
        cb(null, browser);
    });

};

This is the test file which i have named as *spec.js*

var getBrowser = require('./helper.js');
describe('setting firefox profile', function() {
    it ('newtab.url is changed', function() {

        getBrowser( function (err, browser) {

            browser.get("https://xyz.com/");

            var usernameloc = element(by.id('username'));
            var passwordloc = element(by.id('password'));
            var signButtonloc = element(by.id('signinButton'));

            usernameloc.sendKeys("User");
            passwordloc.sendKeys("Password1@");
            signButtonloc.click();


            browser.sleep(7000);

            element(by.linkText('Job Reports')).click();

            browser.sleep(7000);

            element(by.xpath(".//*[@id='ng-app']/body/div[1]/div/div/div/div[1]/rh-rpts-list/div/div[2]/div[4]/div")).click();

            browser.sleep(5000);

            element(by.xpath(".//*[@id='ng-app']/body/div[1]/div/div/div/div[2]/rh-rpts-details/div[3]/rh-rpts-details-toolbar/div/div/table/tbody/tr[1]/td[3]/div/a")).click();

            browser.sleep(20000);

        });

    });
});


Below is the configuration file Config.js.

xports.config = {
   // directConnect: true,

    seleniumAddress:'http://localhost:4444/wd/hub',


   // specs: ['spec.js'],

    framework: 'jasmine2',

    specs: ['spec.js'],

    capabilities: {
       // 'browserName:'chrome',
        'browserName': 'firefox'
       // 'firefox_profile': fp,
    },


 //   getMultiCapabilities: helper.getFirefoxProfile,

    jasmineNodeOpts: {
        showcolor: true,
        defaultTimeoutInterval: 300000
    }
};

Thanks in advance.
Meenakshi

**Comment by saadtazi** [comment]
Your test is asynchronous, you have to use `done` callback:

```it('....', function (done) {
  // call done function at some point...
..}
```

**Comment by meenakshidembi** [comment]
Hi,
I tried that also it is still not working.

**Comment by saadtazi** [comment]
Can you post the modified code here? I'll take a closer look.

**Comment by meenakshidembi** [comment]
Hi,
i am pasting code here.

describe('setting firefox profile', function() {
    it ('newtab.url is changed', function(done) {

        getBrowser( function (err, browser) {

            browser.get("https://xyz.com/");

            var usernameloc = element(by.id('username'));
            var passwordloc = element(by.id('password'));
            var signButtonloc = element(by.id('signinButton'));

            usernameloc.sendKeys("xyz");
            passwordloc.sendKeys("Password1@");
            signButtonloc.click();


            browser.sleep(7000);

            element(by.linkText('Job Reports')).click();

            browser.sleep(7000);

            element(by.xpath(".//*[@id='ng-app']/body/div[1]/div/div/div/div[1]/rh-rpts-list/div/div[2]/div[4]/div")).click();

            browser.sleep(5000);

            element(by.xpath(".//*[@id='ng-app']/body/div[1]/div/div/div/div[2]/rh-rpts-details/div[3]/rh-rpts-details-toolbar/div/div/table/tbody/tr[1]/td[3]/div/a")).click();

            browser.sleep(20000);

            done();

        });

    });
});

**Comment by saadtazi** [comment]
Thanks, I'll take a closer look tonight, but a quick comment: if you are using `protractor` (based on the error you posted above), you should not use `wd` to get a browser.
Wdjs is an implementation of selenium webdriver, but Protractor has its own implementation of webdriver. So I think the main problem you are having (if we ignore the async issue)  is to find out how to pass a firefox_profile to protractor webdriver browsers.

FYI: the angular error you posted is because protractor is made to test angular apps by default, and waits for angular to be ready. If you don't have angular, then you have to add the following:
```
beforeEach(function() {
  return browser.ignoreSynchronization = true;
});
```
(See http://stackoverflow.com/questions/28808463/what-is-browser-ignoresynchronization-in-protractor)

**Comment by saadtazi** [comment]
I found this example: how to setup firefox_profile with protractor: https://github.com/juliemr/protractor-demo/tree/master/howtos/setFirefoxProfile

So I think you have all the pieces to fix tour problem now. Let me know if you still need help.
