### ISSUE TITLE
wrench is deprecated

### ISSUE THREAD

**Issue by wagnerand** [saadtazi/firefox-profile-js#61]
`npm install` outputs:

npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.

**Comment by saadtazi** [comment]
Thanks for reporting this.

I'll fix it when I'll get back from vacation.

**Comment by saadtazi** [comment]
I actually managed to work on it and just published v0.4.0.

**Comment by wagnerand** [comment]
Thank you!
