### ISSUE TITLE
Temporary files not deleted even when using "shouldDeleteOnExit(true)"

### ISSUE THREAD

**Issue by jrharshath** [saadtazi/firefox-profile-js#62]
I see that when running firefox using protractor, several directories with the name pattern `/tmp/tmp-<random>` are created in addition to the profile directory (which is returned by `FirefoxDriver.prototype.path`).

When using `shouldDeleteOnExit(true)` to create the profile, I see that the profile directory gets deleted. However the `tmp-*` files do not get cleaned up. I think that should also get deleted when this flag is enabled.

**Comment by jrharshath** [comment]
I did some more digging. Here's what I found:

1. On each run, there are four directories created in /tmp: two with the name pattern `tmp-<random>`, and two with names that look like GUIDs
2. calling [`path()`](https://github.com/saadtazi/firefox-profile-js/blob/master/doc/firefox_profile.md#firefoxprofileprototypepath) return sthe path to one of the GUID-named directories.
3. The [`_cleanOnExit`](https://github.com/saadtazi/firefox-profile-js/blob/master/doc/firefox_profile.md#firefoxprofileprototype_cleanonexit) method deletes the GUID-named directory that is found by calling `path()`, and one of the two `tmp-<random>` directories.
4. However, if `shouldDeleteOnExit` is set to false, none of the directories I mentioned in step 1 are deleted on exit.

**Comment by saadtazi** [comment]
Thanks for providing more information.

Unfortunately, I will be able to take a look at this issue only next week-end.

In the meantime: can you confirm that the `/tmp/tmp-<random>` is created by `firefox-profile`? I can't find in firefox-profile a place where `/tmp/tmp-<random>` folders would be created. maybe `protractor` is creating those directories?

**Comment by jrharshath** [comment]
I'm not sure whether the `/tmp/tmp-<random>` is created by firefox, firefox-profile or protractor. Any ideas how to narrow track it down?

For now, here's a workaround I'm using: when launching protractor, I'm setting the `TMPDIR` environment variable to a newly created directory. This causes all temporary files to be created in that directory. Once protractor is done, I simply delete that directory and went on my merry way.

**Comment by saadtazi** [comment]
I think I can easily check if it's `(firefox-profile + firefox)`. I'll give it a try tonight :finger_crossed:

**Comment by saadtazi** [comment]
What I found on my Mac when running [this example](https://github.com/saadtazi/firefox-profile-js/blob/master/examples/example-wd.js):
- `/var/folders/k5/0blwg61n6j93w_35dspfc5w00000gn/T/` is the tmp directory used by nodejs (`node -e "console.log(os.tmpDir())"`).
- `fp.path()` directory  is created then deleted (when `shouldDeleteOnExit`): `/var/folders/k5/0blwg61n6j93w_35dspfc5w00000gn/T/7056b70c-d73c-48d8-aac9-addfb2f455c2`.
- I looked inside my tmp directory (``/var/folders/k5...`), also inside `/tmp` too, I can't find a directory with the `tmp-<random>`.

Can you run the same test: 
```
// this requires to have selenium server running... 
// I am using selenium-standalone npm package for that
cd node_modules/firefox-profile/examples/
node ./example-wd.js
```
A firefox window should open (and should remain open even after the script has finished running).
Let me know if you have that extra `/tmp/tmp-<random>` directory before and after closing firefox.

Important question I guess 😉 : Which OS are you using?

**Comment by saadtazi** [comment]
I will close for now (no answers). Feel free to reopen/add a comment if you still have issues.
