### ISSUE TITLE
Empty profile creation doesn't behave as expected

### ISSUE THREAD

**Issue by gregglind** [saadtazi/firefox-profile-js#64]
```
./node_modules/.bin/firefox-profile -v   -o `pwd`/A
```

I claim:

- should create a profile at A, with the default `user.js` 

Why this doesn't?   `cli.js`  does this instead

```
  cb(null, new FirefoxProfile({
    destinationDirectory: destinationDirectory
  }));
```

Which never actually makes any files, unless it is copying from an existing profile.

Ideas for solving this welcome :)

Use case:  I need blank, portable profiles for re-using during test-runs of addons.

**Comment by gregglind** [comment]
Amended like this:

```
    if (!encoded) {
      // we're done
      fp.updatePreferences();
```

which now (as expected) throws errors because the directory doesn't exist :)

(doing this all with raw `fs` calls is tedious.  Maybe a tree utility would help?

**Comment by saadtazi** [comment]
Thanks for reporting the issue.. and sorry for the delay.

I applied the suggested patch in new version 0.4.1.

Regarding your comment about using a tree utility: this, the fact that this lib doesn't use promises, plus other "beginner's mistakes": So many things to do, so little time :).
This library is my first contribution to npm, my first personal open source project, when I was starting playing with nodejs. One day, I might decide to rewrite firefox-profile from scratch... maybe...
