### ISSUE TITLE
selenium-webdriver for Firefox wants to encode profile object which is encoded

### ISSUE THREAD

**Issue by danzaner** [saadtazi/firefox-profile-js#66]
Hi.... thanks for creating firefox-profile. It's been helpful. I ran into one issue that I figured I'd let you and your users know about. Maybe I'm just doing something wrong, but when I pass the "capabilities" object into selenium-webdriver, /selenium-webdriver/firefox/index.js eventually attempts to encode your module's profile object, which is already encoded before being passed in.

I'm using selenium-webdriver v3.0.0-beta-2

On line 486 of the firefox/index.js file, there is this set:
caps.set(Capability.PROFILE, profile.encode());

Your profile object doesn't have an encode() function, so an error is thrown. In your examples, you have us call .encoded() on the profile and then set the encoded object that we get back in the callback as the 'firefox_profile' of the capabilities object. It's already encoded by the time selenium's code tries to encode it with a function that doesn't exist on your object.

To get around this, I had to patch line 486 in the selenium driver file to:
caps.set(Capability.PROFILE, profile);

Obviously, that's a bad workaround since it breaks updates of selenium and I guess violates their idea of what functions a profile object should have. It would probably be much better if you added a synchronous function called "encode()" that does exactly what "encoded()" does asynchronously. If a synchronous function would be bad for some reason (sorry, I haven't read all of your code) maybe you could hack it with "encoded()" setting a flag on the object, and "encode()" just returning the profile object itself if the flag is set?

Thanks again for your work, and if there is some option I don't know about to get around this issue correctly, I'd appreciate hearing about it.

Best,
Dan

**Comment by danzaner** [comment]
I was just curious, so I took a look at modifying your code rather than Selenium's. I see now that you are just giving Selenium a Base64 encoded string. So, in 'encoded()', I saved a copy of 'content' on the profile itself, and then added an "encode()" method that just returns the Base64 version of 'content'. Works fine. About the only thing I'd change further to avoid confusion is to just rename "encoded()" to something like "preprocess()" or "prepareProfile()" or something else.

**Comment by saadtazi** [comment]
(Not in front of a computer, so take my answer with a grain of salt)

When I created this livrary, selenium didn't have the ability to create firefox profile. So i ported the official python selenium Profile class into nodejs.

But I think that now nodejs selenium package has a Profile class, that you could also use. It's this class that has an ˋencode()ˋ method.

The name ˋencoded()` comes from the python class.

I'll take a closer look later.  you can also check the examples folder.

**Comment by saadtazi** [comment]
selenium-webdriver Profile class is documented [here](http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/firefox/profile_exports_Profile.html).

Example on how to use it (from [here](http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/firefox/index.html)):
```
var firefox = require('selenium-webdriver/firefox');

 var profile = new firefox.Profile();
 profile.addExtension('/path/to/firebug.xpi');
 profile.setPreference('extensions.firebug.showChromeErrors', true);

 var options = new firefox.Options().setProfile(profile);
 var driver = new firefox.Driver(options);
```

All of this is not related to `firefox-profile`. If you still want to use `firefox-profile` with `selenium-webdriver`, let me know: [this `firefox-profile` example](https://github.com/saadtazi/firefox-profile-js/blob/master/examples/example.js) might not work with newer version of `selenium-webdriver`.

**Comment by danzaner** [comment]
Thanks a ton for all the info! Your class does work as long as it gets an .encode() method. I'll look at the selenium docs. I just wish their docs were a bit better organized around basic use cases. Thanks again!

**Comment by saadtazi** [comment]
>  Your class does work as long as it gets an .encode() method

Good point. I added a `encode` method (alias of `encoded`) in `firefox-profile 4.2`.
