### ISSUE TITLE
Error: profile.getTemplateDir is not a function when set firefox profile in Protractor

### ISSUE THREAD

**Issue by tamvo94** [saadtazi/firefox-profile-js#82]
I try to use this code with directConnect: true:
```
var makeFirefoxProfile = function (preferenceMap) {
  var deferred = q.defer();
  var firefoxProfile = new FirefoxProfile();

  for (var key in preferenceMap) {
    firefoxProfile.setPreference(key, preferenceMap[key]);
  }

  firefoxProfile.encoded(function (encodedProfile) {
    var capabilities = {
      browserName: "firefox",
      firefox_profile: encodedProfile
    };

    deferred.resolve(capabilities);
  });
  return deferred.promise;
};

  getMultiCapabilities: function () {
    return q.all([
      makeFirefoxProfile(
        {
          "browser.download.folderList": 2,
          "browser.download.dir": "D:/Automation",
          "browser.helperApps.alwaysAsk.force": false
        }
      )
    ]);
  },
```
But it show error when start server: 

> Error: TypeError: profile.getTemplateDir is not a function

> at createGeckoDriver (node_modules\protractor\node_modules\selenium-webdriver\firefox\index.js:479:17)
>     at Function.createSession (node_modules\protractor\node_modules\selenium-webdriver\firefox\index.js:631:14)

I have wonder that profile = caps.get(Capability.PROFILE) return string, and getTemplateDir() {return this.template_;} is function in class Profile at node_modules\protractor\node_modules\selenium-webdriver\firefox\index.js
 I don't know how to fix it.
More info:
- Gecko driver: 0.14
- Firefox-profile: 0.48
- Selenium-webdriver: 3.0.1
- Protractor: 5.1.1
- Firefox version: 51

**Comment by saadtazi** [comment]
Hi @tamvo94 ,
I saw that you posted on [stackoverflow](https://stackoverflow.com/questions/42151372/error-typeerror-profile-gettemplatedir-is-not-a-function-when-set-firefox-prof). I also found this issue on [protractor repo](https://github.com/angular/protractor/issues/4088)...

I feel like there is a mix of firefoxProfile from `selenium-webdriver` package and from `firefox-profile` package... Which are 2 different ways to generate firefox profile.

I am not really familiar with latest versions of protractor andhow it handles firefox profiles... Do you have a repo with the minimal setup that reproduces the issue?

Thank you,

Saad

**Comment by tamvo94** [comment]
Hi, please see my repo: 
https://github.com/tamvo94/config-firefox
You can reprodure it.
Can you help me fix it? 
I'm needed urgently. Thanks :)

**Comment by saadtazi** [comment]
If you only pass user prefs, then you should not need `firefox-profile`: see [this](http://www.protractortest.org/#/browser-setup)

**Comment by tamvo94** [comment]
I need to set download files path in FF, so I set firefox profile to do it.
So can I remove firefox-profile that I can set  "browser.download.dir"????
Thanks.

**Comment by saadtazi** [comment]
So this is how you should fix it: 
```
var FirefoxProfile = require("selenium-webdriver/firefox").Profile;

var makeFirefoxProfile = function (preferenceMap) {
  // var deferred = q.defer();
  // var firefoxProfile = new FirefoxProfile();
  //
  // for (var key in preferenceMap) {
  //   firefoxProfile.setPreference(key, preferenceMap[key]);
  // }
  //
  // firefoxProfile.encoded(function (encodedProfile) {
  //   var capabilities = {
  //     browserName: "firefox",
  //     marionette: true,
  //     firefox_profile: encodedProfile
  //   };
  //
  //   deferred.resolve(capabilities);
  // });
  // return deferred.promise;
  var profile = new FirefoxProfile();
  for (var key in preferenceMap) {
    profile.setPreference(key, preferenceMap[key]);
  }
  return q.resolve({
    browserName: "firefox",
    marionette: true,
    firefox_profile: profile
  });
};
```

(I can see the settings in `about:config` page).

Why: now `selenium-webdriver` expects a `selenium-webdriver/firefox` `Profile` instance when a `firefox_profile` is provided. In the past, it was expecting a base64 encoded firefox profile. THey probably changed that when they introduced the ability to create firefox profiles in `selenium-webdriver`.

Note that this has nothing to do `firefox-profile`. **You don't need `firefox-profile` now that selenium-webdriver introduced `firefox.Profile`**

**Comment by tamvo94** [comment]
```
 path must be a string or Buffer
[11:45:33] E/launcher - TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.readdirSync (fs.js:951:18)
```
OK, thank you, I will try research on this.

**Comment by tamvo94** [comment]
Thank you for your support <3.
I can use firefox profile to set anything.
You can close this issue if you have anything else

**Comment by tamvo94** [comment]
Hi,
I add extension for this firefox profile, but the seem, firefox cannot install it and cannot setPreference both.
```
  var firefoxExtension = "./extension/firefox_integration/sample.xpi";
  firefoxProfile.addExtension(firefoxExtension);
  return q.resolve({
    browserName: 'firefox',
    marionette: true,
    firefox_profile: firefoxProfile
  });
```
I also set available profile but it cannot work.
 `var firefoxProfile = new FirefoxProfile("C:/Users/.../AppData/Roaming/Mozilla/Firefox/Profiles/avbq6r8s.TamVo");`
I did not know how wrong???

**Comment by saadtazi** [comment]
@tamvo94, like I mentioned, you no longer need `firefox-profile` package in your project. Now, you have to refer to [`selenium-webdriver` documentation](http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver) (and the [`firefox/profile`](http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/firefox/index.html) class...).

I am not sure how firefox extension works with `selenium-webdriver` `profiles`... 

The `selenium-webdriver` documentation shows that the Profile constructor seems to accept an `opt_str` params, which is a `Path to an existing Firefox profile directory to use a template for this profile. If not specified, a blank profile will be used`... But you'll have to ask your questions to the `selenium-webdriver` folks using those resources (found [here](http://seleniumhq.github.io/selenium/docs/api/javascript/#documentation)):
```
- the #selenium channel on freenode IRC
- the selenium-users@googlegroups.com list
```

Good luck
