### ISSUE TITLE
Getting an error - getTemplateDir() is not a function

### ISSUE THREAD

**Issue by ORESoftware** [saadtazi/firefox-profile-js#86]
I have this:

```js
   fp.encoded(function (encodedProfile) {
      capabilities.set('firefox_profile', encodedProfile);
      var wd = new webdriver.Builder().withCapabilities(capabilities).build();  /// errors here
      resolve(wd);
    });
```

I get an error:

```
 TypeError: profile.getTemplateDir is not a function
       at createGeckoDriver (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/selenium-webdriver/firefox/index.js:506:17)
       at Function.createSession (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/selenium-webdriver/firefox/index.js:658:14)
       at createDriver (/Users/alexamil/WebstormProjects/cisco/cdt-now/node_modules/selenium-webdriver/index.js:167:33)
       at /Users/alexamil/WebstormProjects/cisco/cdt-now/test/e2e/all/export.test.js:40:71
```

here is the broader context if it helps:

```js
  const {By, until, promise} = webdriver;
  promise.USE_PROMISE_MANAGER = true;

  let fp = new FirefoxProfile();
  fp.setPreference('browser.download.folderList', 2);
  fp.setPreference('browser.download.manager.showWhenStarting', false);
  fp.setPreference('browser.download.dir', process.env.HOME + '/cdt_test_data_dir');
  fp.setPreference('browser.helperApps.neverAsk.saveToDisk', 'application/x-gzip');
  fp.updatePreferences();

  let driverPromise = new Promise(function (resolve) {

    let capabilities = webdriver.Capabilities.firefox();
    fp.encoded(function (encodedProfile) {
      capabilities.set('firefox_profile', encodedProfile);
      let wd = new webdriver.Builder().withCapabilities(capabilities).build();
      resolve(wd);
    });
    
  });
```

**Comment by ORESoftware** [comment]
I stepped into the code, error is here:

```js
  if (profile) {
    // If the user specified a template directory or any extensions to install,
    // we need to encode the profile as a base64 string (which requires writing
    // it to disk first). Otherwise, if the user just specified some custom
    // preferences, we can send those directly.
    if (profile.getTemplateDir() || profile.getExtensions().length) {  // <<<< here
      firefoxOptions['profile'] = profile.encode(); 

    } else {
      let prefs = profile.getPreferences();
      if (Object.keys(prefs).length) {
        firefoxOptions['prefs'] = prefs;
      }
    }
  }
```

**Comment by ORESoftware** [comment]
LOL I did some more debugging  - profile in the codebase is a string, like so:

`'UEsDBBQACAAIAPAOiEoAAAAAAAAAAAAAAAAHAAAAdXNlci5qc5VWPW/bMBDd+ysKTy1Q0W2CLO2UJh0KBMiQBh0JijxZjCmSIE+W3V/fo2QlliXL8SYb7933vWMdIXAfoPi0EN6z2iuBwESNbvHlYyFMhM8/PtSTILAiN6CmcXlwDbGYco01TihWCStW9EcsXfO3BPuEIqC2q3n6r+eHW+Y2EIJWQFAM9VFAvaMWec2ElOCxjeo01mi7Zs6D5bBFCFYYMn01TLS3+4a10DTaUkKnwa4oCJ8CnShdbzGKAtpvyp69q4gRRJDlvjnTxlMiNmpnI8uNk2ujI77XeGx56AKwALGugBfBVVwGEctpb6+plGAMkyXI9T0Uojb4s+v7PA1FHlkjgn20d8bFM/U6QD9Sz+ZNxzRWtWeeho2QX6ebOmhBJQzFAvPV6u2WroJkmzdgJH3zOqThWYjc1fg9N8KuF0OfCjbonImMhtgFSR1y5tDZeEyVq5jSMW0Xb6dU1YFmhac9ms7+oPtpde878pMkdiTGt6MyHMCNW62GcziO5wC+14fZqR3DrUNd7J5JD6bDt4CNC+u9RmT7Lcqo5lin+CeWqaeUiJ5424wKa0Fi2oDMQ8jIGcnGRPIDpi91LHdZEjgvYswM2BWmob+6uRm2sQ+KVDIyYYxreL7jqpt6IozL5mmJPEZG88srp4Q5M2Egqc24Y4U2QF/MBU2t4d4ZLXfk4XoYUDzGRwxaIj+mTRTvlZp2kIMlDUzz1f59YhlnKa2oc2flZeQGxJryen+AiXCZLwNic1lqQ8Zl3mKdVxq5tu+v5EYDHZUVr/T21Ckdln5AOBueXllnSdUrqHIIT+3PExuVRGqtke33o7/XeyGanPCegmDIA4bd/ISP4d2KtIkfnd8xNsAL7feJy/4iNiLKoD3SXW9FoC3Nb3vX6e1k+P0VS3rbXXam6sofJDFe6gZyFTQpC+9eGry2BIoUF5cQMNV2jtQJJ7cCyQaHDe3eOQrJUjrJb340/dEq29hRyoTEkHel4KG2HHWVtvL66AS85b5/nxXOKAgP9Gwg9FEzRmClk7IulknS41IY2IpKm6VUyBEicnpECp5AQ8nq7dCrgST6NimppRqE20hrLTbwJ12uJAnpLUqqR1VydrnNVv+0T6b+A1BLBwh5+eL0RQMAAK0KAABQSwECLQMUAAgACADwDohKefni9EUDAACtCgAABwAAAAAAAAAAACAApIEAAAAAdXNlci5qc1BLBQYAAAAAAQABADUAAAB6AwAAAAA='`
LOL no idea what's going on

**Comment by saadtazi** [comment]
Please refer to this issue: https://github.com/saadtazi/firefox-profile-js/issues/82

Long story short: now that selenium-webdriver (nodejs) added support for firefox profile, you should not use firefox-profile library with selenium-webdriver.

I should update examples and readme file...

**Comment by ORESoftware** [comment]
ahhh, thanks for the info, I understand - I didn't see any docs on how to use firefox profile with selenium-webdriver, and that's when I found this library. I guess this is what I am looking for:

http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/firefox/index.html

**Comment by saadtazi** [comment]
Yep!

FYI: why is it a string? Firefox webdriver expects the profile capabilities to be a base64 representation of a zip of the profile directory (if that makes sense...)

https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities#firefox-specific
