### ISSUE TITLE
Error importing firefox profile

### ISSUE THREAD

**Issue by sky-joaonabais** [saadtazi/firefox-profile-js#89]
Hi,

I'm automating some tests that require a base64 firefoxProfile to be imported (see https://github.com/mozilla/geckodriver/issues/755). I've used the CLI to create it, like this:

`node_modules/.bin/firefox-profile -c firefoxProfile -b`

However when running the tests the following Error is thrown:
`ERROR: Last unit does not have enough valid bits`

I'm running selenium-standalone both in node and hub, more info:

Versions: Selenium standalone : 3.4.0
Geckodriver : 0.16.1
Firefox (Windows) : 53.0.3

I'm importing the profile in the config of webdriver.io:

```const FIREFOX = {
  maxInstances: 5,
  browserName: 'firefox',
  marionette: true,
  acceptInsecureCerts: true,
  log: {
    level: 'trace'
  },
  'moz:firefoxOptions': {
    profile: 'profileBase64'
  }
};
```

I've generated the `firefoxProfile` forlder following the steps specified in:  
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles#w_creating-a-profile

I'm running selenium-standalone hub on Mac OS X 10.11 and the node on Windows10, I've tried to create the profile on both systems and run the tests on the same machine that is running the hub.

the config is imported, since I get the following on the node log:

```
09:45:31.206 INFO - Creating a new session for Capabilities [{rotatable=true, marionette=true, log={level=trace}, acceptInsecureCerts=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@6448c9d7, locationContextEnabled=true, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, moz:firefoxOptions={profile=profileBase64}, maxInstances=5, requestOrigins={name=webdriverio, version=4.6.2, url=http://webdriver.io}}]
```

Not sure what I' doing wrong should I be passing any other option when running the CLI on terminal?

Thanks.

**Comment by sky-joaonabais** [comment]
My bad [geckodriver](https://github.com/mozilla/geckodriver) expects a zip file:

```
profile	string	Base64-encoded zip of a profile directory to use as the profile for the Firefox instance. This may be used to e.g. install extensions or custom certificates. By default, a new profile will be created in the system’s temporary folder. The effective profile in use by the WebDriver session is returned to the user in the `moz:profile` capability.
```

**Comment by saadtazi** [comment]
Hi @sky-joaonabais,
Glad that you no longer have an error. Did you solve all the issues you had? Can Ee close this issue?
