### ISSUE TITLE
Update home link

### ISSUE THREAD

**Issue by DMarinsa** [saadtazi/firefox-profile-js#97]
Hello, could you update your link to selenium-webdriver's link to the example in Selenium hq, it's broken, thanks!

http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/firefox/index.html

**Comment by saadtazi** [comment]
OOps, sorry, totally missed this issue. The link has been fixed on master branch. For reference: http://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/firefox.html
